[colors]
[colors.primary]
background = "#000000"
foreground = "#c1c1c1"

[colors.cursor]
text   = "#000000"
cursor = "#c1c1c1"

[colors.selection]
text = "#c1c1c1"
background = "#333333"

[colors.normal]
black   = "#1c1c1c"
red     = "#8a9a7b"
green   = "#c1c1c1"
yellow  = "#888888"
blue    = "#aaaaaa"
magenta = "#999999"
cyan    = "#aa9988"
white   = "#c1c1c1"

[colors.bright]
black   = "#505050"
red     = "#8a9a7b"
green   = "#c1c1c1"
yellow  = "#888888"
blue    = "#aaaaaa"
magenta = "#999999"
cyan    = "#aa9988"
white   = "#ffffff"
