# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#c1c1c1"

# Title color for boxes
theme[title]="#c1c1c1"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8a9a7b"

# Background color of selected item in processes box
theme[selected_bg]="#505050"

# Foreground color of selected item in processes box
theme[selected_fg]="#8a9a7b"

# Color of inactive/disabled text
theme[inactive_fg]="#505050"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#c1c1c1"

# Background color of the percentage meters
theme[meter_bg]="#505050"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c1c1c1"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#999999"
theme[mem_box]="#c1c1c1"
theme[net_box]="#8a9a7b"
theme[proc_box]="#8a9a7b"

# Box divider line and small boxes line color
theme[div_line]="#505050"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#c1c1c1"
theme[temp_mid]="#888888"
theme[temp_end]="#8a9a7b"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#aa9988"
theme[cpu_mid]="#aaaaaa"
theme[cpu_end]="#999999"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#999999"
theme[free_mid]="#aaaaaa"
theme[free_end]="#aa9988"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#aaaaaa"
theme[cached_mid]="#aa9988"
theme[cached_end]="#999999"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#888888"
theme[available_mid]="#8a9a7b"
theme[available_end]="#8a9a7b"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#c1c1c1"
theme[used_mid]="#aa9988"
theme[used_end]="#aaaaaa"

# Download graph colors (Peach -> Red)
theme[download_start]="#888888"
theme[download_mid]="#8a9a7b"
theme[download_end]="#8a9a7b"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#c1c1c1"
theme[upload_mid]="#aa9988"
theme[upload_end]="#aaaaaa"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#aa9988"
theme[process_mid]="#aaaaaa"
theme[process_end]="#999999"
