# Background and foreground colors
background = #000000
foreground = #c1c1c1
cursor-color = #c1c1c1
selection-background = #333333
selection-foreground = #c1c1c1

# Standard colors
palette = 0=#1c1c1c
palette = 1=#8a9a7b
palette = 2=#c1c1c1
palette = 3=#888888
palette = 4=#aaaaaa
palette = 5=#999999
palette = 6=#aa9988
palette = 7=#c1c1c1

# Bright colors
palette = 8=#505050
palette = 9=#8a9a7b
palette = 10=#c1c1c1
palette = 11=#888888
palette = 12=#aaaaaa
palette = 13=#999999
palette = 14=#aa9988
palette = 15=#ffffff
