background            #000000
foreground            #c1c1c1
selection_foreground  #c1c1c1
selection_background  #333333

cursor                #c1c1c1
cursor_text_color     #000000

active_border_color   #8a9a7b
active_tab_background #8a9a7b

# black
color0  #1c1c1c
color8  #505050

# red
color1  #8a9a7b
color9  #8a9a7b

# green
color2  #c1c1c1
color10 #c1c1c1

# yellow
color3  #888888
color11 #888888

# blue
color4  #aaaaaa
color12 #aaaaaa

# magenta
color5  #999999
color13 #999999

#cyan
color6  #aa9988
color14 #aa9988

#white
color7  #c1c1c1
color15 #ffffff
